services:
  - type: web
    name: voteku-test-system
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix admin && npm run build --prefix admin
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://voteku-test-system.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: voteku-db
          property: connectionString
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENT
        value: n.krokhmal@gmail.com, brutdx@gmail.com

databases:
  - name: voteku-db
    databaseName: voteku
    plan: free
    user: voteku
